
  services:
    postgres:
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_USER: esteban
        POSTGRES_PASSWORD: 123456Aa.
        POSTGRES_DB: dmh
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      depends_on:
        - postgres
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/dmh
        KC_DB_USERNAME: esteban
        KC_DB_PASSWORD: 123456Aa.
        KC_DB_URL_PROPERTIES: ssl=false
      ports:
        - "8080:8080"
      command: start-dev
    gateway:
      build: ./gateway
      ports:
        - 8081:8080
      depends_on:
        - user-service
        - property-service

    user-service:
      build: ./user-service
      ports:
        - 8082:8080

    property-service:
      build: ./property-service
      ports:
        - 8083:8080

volumes:
  postgres_data:

