package org.esteban.lescano.dmhouse.enums;

public enum ResultadoTransaccionEnum {
    NEGATIVE_IMPORT_ERROR,
    INITIATED,
    INSUFFICIENT_BALANCE,
    DESTINATION_WALLET_NOT_FOUND,
    SOURCE_WALLET_NOT_FOUND,
    DAILY_LIMIT_REACHED,
    NONEXISTENT_ORIGIN_ACCOUNT,
    NONEXISTENT_DESTINATION_ACCOUNT,
    WILL_WANT_TO_PAY_ITSELF,
    NONEXISTENT_DESTINATION_EMAIL
}
