spring.application.name=gateway-keycloack
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/dmhouse
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=dmhouse-cliente
jwt-auth-converter.principal-atribute=preferred_username
spring.main.allow-bean-definition-overriding=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG